let items=[
   { ImageUrl:'B:\rtrppics\butterchiken.jpg',
    name:"Butter Chicken",
    price:220,
    discription:"Butter chicken, or Murgh Makhani, is a popular North Indian dish featuring tender chicken pieces in a rich, creamy tomato-based sauce. ",
    category:"Non-veg",
    rating:4.5
   },
   { ImageUrl:'B:\rtrppics\chickentikkamasala.jpg',
      name:"Chicken Tikka Masala",
      price:250,
      discription:"Chicken Tikka Masala is a popular Indian dish consisting of marinated, grilled chicken pieces (tikka) cooked in a spiced, creamy tomato sauce. The sauce includes ingredients like tomatoes, cream, onions, garlic, ginger, and a blend of spices such as garam masala and turmeric.",
      category:"Non-veg",
      rating:3.5
     },
     { ImageUrl:'B:\rtrppics\dosa.jpg',
      name:"Dosa",
      price:60,
      discription:"Dosa is a popular South Indian dish made from a fermented batter of rice and urad dal (black gram). It is a thin, crispy crepe served with accompaniments like sambar (a spicy lentil soup) and coconut chutney. Dosa can be plain or filled with spiced potato mixture, known as masala dosa.",
      category:"veg",
      rating:2.2
     },
     { ImageUrl:'B:\rtrppics\potatocurry.jpg',
      name:"Potato",
      price:60,
      discription:"The potato is a starchy tuber from the plant Solanum tuberosum. It is a versatile vegetable used in various cuisines worldwide. Potatoes can be boiled, baked, fried, mashed, or roasted and are commonly used in dishes like fries, mashed potatoes, and stews.",
      category:"veg",
      rating:1.3
     },
     { ImageUrl:'B:\rtrppics\brinjal.webp',
      name:"Brinjal",
      price:70,
      discription:"Brinjal, also known as eggplant or aubergine, is a glossy, purple vegetable from the nightshade family. It has a spongy texture and mild flavor, making it versatile in cooking. ",
      category:"veg",
      rating:2.6
     },
     { ImageUrl:'B:\rtrppics\chapathi.jpg',
      name:"Chepathi",
      price:50,
      discription:"Chapati is a type of unleavened flatbread from India, made from whole wheat flour (atta), water, and salt. The dough is rolled into thin discs and cooked on a hot griddle (tava) until it puffs up and develops brown spots. Chapatis are soft and pliable, often served with curries, vegetables, or dals.",
      category:"veg",
      rating:3.6
     },
     { ImageUrl:'B:\rtrppics\grilledthandoorichicken.jpg',
      name:"Grilled Thandoori Chicken",
      price:350,
      discription:"Tandoori Chicken begins with marinating chicken pieces (usually drumsticks, thighs, or breast) in a mixture of yogurt and spices. The marinade typically includes ingredients like ginger-garlic paste, cumin, coriander, turmeric, cayenne pepper, and garam masala.",
      category:"Non-veg",
      rating:2.4
     },
     { ImageUrl:'B:\rtrppics\fishbiryani.webp',
      name:"FishBiryani",
      price:350,
      discription:"Fish Biryani starts with marinating pieces of firm fish (such as cod, tilapia, or salmon) in a blend of yogurt, spices like turmeric, chili powder, and garam masala, along with ginger-garlic paste. ",
      category:"Non-veg",
      rating:3.5
     },
     { ImageUrl:'B:\rtrppics\eggbiryani.jpg',
      name:"EggBiryani",
      price:320,
      discription:"gg Biryani is a flavorful rice dish from South Asian cuisine where hard-boiled eggs are cooked with fragrant basmati rice and a blend of spices. The dish typically includes onions, tomatoes, garlic, ginger, and spices like cumin, coriander, turmeric, and garam masala. ",
      category:"Non-veg",
      rating:2.5
     },
     { ImageUrl:'B:\rtrppics\icecream.webp',
      name:"Icecream",
      price:100,
      discription:"Ice cream is a frozen dessert made from cream, milk, sugar, and typically flavored with various ingredients such as vanilla, chocolate, fruits, nuts, or cookies.",
      category:"veg",
      rating:2.2
     },
     { ImageUrl:'B:\rtrppics\momos.jpg',
      name:"Momos",
      price:250,
      discription:"Momos are a type of steamed or fried dumpling originating from Tibet and commonly found in Nepali, Tibetan, and other Himalayan cuisines. They are typically filled with a mixture of minced meat (such as pork, chicken, or lamb) or vegetables, along with garlic, ginger, and spices. ",
      category:"veg",
      rating:3.3
     },
     { ImageUrl:'B:\rtrppics\muttonpulav.jpg',
      name:"Muttonpulao",
      price:450,
      discription:"Mutton Pulao, also known as Mutton Pulav or Mutton Pilaf, is a flavorful rice dish from South Asian cuisine. It features tender pieces of mutton (goat meat) cooked with fragrant basmati rice and a blend of aromatic spices.",
      category:"Non-veg",
      rating:1.8
     },
     { ImageUrl:'B:\rtrppics\palakpaneer.jpg',
      name:"Palakpaneer",
      price:220,
      discription:"Palak Paneer is a popular North Indian dish made with paneer (Indian cottage cheese) cooked in a creamy spinach (palak) gravy. The spinach is blanched, pureed, and cooked with onions, tomatoes, garlic, ginger, and a blend of spices such as cumin, coriander, turmeric, and garam masala.",
      category:"veg",
      rating:3.1
     },
     { ImageUrl:'B:\rtrppics\paneerbiryani.jpg',
      name:"PaneerBiryani",
      price:430,
      discription:"Paneer Biryani is a vegetarian variation of the classic biryani dish from South Asian cuisine. It features cubed paneer (Indian cottage cheese) marinated in yogurt and spices, layered with fragrant basmati rice that's been partially cooked with whole spices like cloves, cardamom, and bay leaves. ",
      category:"veg",
      rating:4.1
     },
     { ImageUrl:'B:\rtrppics\paneermakhani.jpg',
      name:"Paneermakhani",
      price:430,
      discription:"Paneer Makhani, also known as Paneer Butter Masala, is a popular North Indian dish. It consists of cubes of paneer (Indian cottage cheese) cooked in a rich and creamy tomato-based sauce. ",
      category:"veg",
      rating:2.3
     },
     { ImageUrl:'B:\rtrppics\pasta.webp',
      name:"Pasta",
      price:330,
      discription:"Pasta is a staple food from Italian cuisine made from unleavened dough of durum wheat flour, mixed with water or eggs. It is shaped into various forms such as spaghetti, penne, fusilli, or ravioli, and then boiled until cooked al dente. ",
      category:"veg",
      rating:3.2
     },
     { ImageUrl:'B:\rtrppics\pastry.jpg',
      name:"Pastry",
      price:130,
      discription:"A pastry is a baked food made from dough that is typically rich in butter or another fat. It can be sweet or savory and comes in various forms such as pies, tarts, croissants, and danishes.",
      category:"veg",
      rating:2.9
     },
     { ImageUrl:'B:\rtrppics\pavbhaji.webp',
      name:"Pavbhaji",
      price:120,
      discription:"Pav Bhaji is a popular Indian street food dish consisting of a spiced vegetable mash (bhaji) served with buttered and toasted bread rolls (pav). The bhaji is made from mashed vegetables like potatoes, peas, tomatoes, and bell peppers cooked with spices such as cumin, coriander, turmeric, and red chili powder. ",
      category:"veg",
      rating:1.2
     },
     { ImageUrl:'B:\rtrppics\pizza.jpg',
      name:"Pizza",
      price:280,
      discription:"Pizza is a popular Italian dish consisting of a round, flat bread base topped with tomato sauce, cheese (usually mozzarella), and various ingredients such as meats (pepperoni, sausage), vegetables (bell peppers, mushrooms), and herbs (basil, oregano). ",
      category:"veg",
      rating:3.5
     },
     { ImageUrl:'B:\rtrppics\samosa.webp',
      name:"Samosa",
      price:80,
      discription:"A samosa is a popular snack originating from the Indian subcontinent. It consists of a crispy, triangular pastry filled with a savory mixture, usually including spiced potatoes, peas, and sometimes meat like minced lamb or chicken.",
      category:"veg",
      rating:2.6
     },
     { ImageUrl:'B:\rtrppics\sandwich.webp',
      name:"Sandwich",
      price:280,
      discription:"A sandwich is a food item consisting of two pieces of bread with various fillings between them. It can be made with a wide range of ingredients such as meats (like ham, turkey, or chicken), cheeses, vegetables (lettuce, tomatoes, cucumbers), spreads (mayonnaise, mustard), and condiments. ",
      category:"veg",
      rating:3.2
     },
     { ImageUrl:'B:\rtrppics\shawarma.png',
      name:"Shawarma",
      price:180,
      discription:"Shawarma is a Middle Eastern street food dish made of thinly sliced marinated meat (often lamb, chicken, beef, or a combination) stacked in a vertical rotisserie. The meat is slowly roasted and shaved off in thin slices as it cooks. ",
      category:"Non-veg",
      rating:2.9
     },
     { ImageUrl:'B:\rtrppics\vegbiryani.jpg',
      name:"Vegbiryani",
      price:220,
      discription:"Veg Biryani is a vegetarian version of the popular South Asian rice dish, biryani. It's made with fragrant basmati rice, mixed vegetables such as carrots, peas, potatoes, and bell peppers, cooked with a blend of spices like cumin, coriander, and garam masala.",
      category:"veg",
      rating:1.2
     },
     { ImageUrl:'B:\rtrppics\vegpulao.jpg',
      name:"Vegpulav",
      price:260,
      discription:"Egg pulao is a flavorful Indian rice dish made with basmati rice, boiled or scrambled eggs, and a blend of spices. The rice is cooked with onions, tomatoes, garlic, ginger, and whole spices like cumin, cardamom, and bay leaves. Garnished with fresh herbs, it is a one-pot meal often served with raita or a side salad.",
      category:"veg",
      rating:3.1
     },
     
     
     
   
]