let items=[
   { ImageUrl:'B:\rtrppics\butterchiken.jpg',
    name:"Butter Chicken",
    price:220,
    discription:"",
    category:"Non-veg",
    rating:4.5
   },
   { ImageUrl:'B:\rtrppics\chickentikkamasala.jpg',
      name:"Chicken Tikka Masala",
      price:250,
      discription:"",
      category:"Non-veg",
      rating:3.5
     },
     { ImageUrl:'B:\rtrppics\dosa.jpg',
      name:"Dosa",
      price:60,
      discription:"",
      category:"veg",
      rating:2.2
     },
     { ImageUrl:'B:\rtrppics\potatocurry.jpg',
      name:"Potato",
      price:60,
      discription:"",
      category:"veg",
      rating:1.3
     },
     { ImageUrl:'B:\rtrppics\brinjal.webp',
      name:"Brinjal",
      price:70,
      discription:"",
      category:"veg",
      rating:2.6
     },
     { ImageUrl:'B:\rtrppics\chapathi.jpg',
      name:"Chepathi",
      price:50,
      discription:"",
      category:"veg",
      rating:3.6
     },
     { ImageUrl:'B:\rtrppics\grilledthandoorichicken.jpg',
      name:"Grinlled Thandoori Chicken",
      price:350,
      discription:"",
      category:"Non-veg",
      rating:2.4
     },
     { ImageUrl:'B:\rtrppics\fishbiryani.webp',
      name:"FishBiryani",
      price:350,
      discription:"",
      category:"Non-veg",
      rating:3.5
     },
     { ImageUrl:'B:\rtrppics\eggbiryani.jpg',
      name:"EggBiryani",
      price:320,
      discription:"",
      category:"Non-veg",
      rating:2.5
     },
     { ImageUrl:'B:\rtrppics\icecream.webp',
      name:"Icecream",
      price:100,
      discription:"",
      category:"veg",
      rating:2.2
     },
     { ImageUrl:'B:\rtrppics\momos.jpg',
      name:"Momos",
      price:250,
      discription:"",
      category:"veg",
      rating:3.3
     },
     { ImageUrl:'B:\rtrppics\muttonpulav.jpg',
      name:"Muttonpulav",
      price:450,
      discription:"",
      category:"Non-veg",
      rating:1.8
     },
     { ImageUrl:'B:\rtrppics\palakpaneer.jpg',
      name:"Palakpaneer",
      price:220,
      discription:"",
      category:"veg",
      rating:3.1
     },
     { ImageUrl:'B:\rtrppics\paneerbiryani.jpg',
      name:"PaneerBiryani",
      price:430,
      discription:"",
      category:"veg",
      rating:4.1
     },
     { ImageUrl:'B:\rtrppics\paneermakhani.jpg',
      name:"Paneermakhani",
      price:430,
      discription:"",
      category:"veg",
      rating:2.3
     },
     { ImageUrl:'B:\rtrppics\pasta.webp',
      name:"Pasta",
      price:330,
      discription:"",
      category:"veg",
      rating:3.2
     },
     { ImageUrl:'B:\rtrppics\pastry.jpg',
      name:"Pastry",
      price:130,
      discription:"",
      category:"veg",
      rating:2.9
     },
     { ImageUrl:'B:\rtrppics\pavbhaji.webp',
      name:"Pavbhaji",
      price:120,
      discription:"",
      category:"veg",
      rating:1.2
     },
     { ImageUrl:'B:\rtrppics\pizza.jpg',
      name:"Pizza",
      price:280,
      discription:"",
      category:"veg",
      rating:3.5
     },
     { ImageUrl:'B:\rtrppics\samosa.webp',
      name:"Samosa",
      price:80,
      discription:"",
      category:"veg",
      rating:2.6
     },
     { ImageUrl:'B:\rtrppics\sandwich.webp',
      name:"Sandwich",
      price:280,
      discription:"",
      category:"veg",
      rating:3.2
     },
     { ImageUrl:'B:\rtrppics\shawarma.png',
      name:"Shawarma",
      price:180,
      discription:"",
      category:"Non-veg",
      rating:2.9
     },
     { ImageUrl:'B:\rtrppics\vegbiryani.jpg',
      name:"Vegbiryani",
      price:220,
      discription:"",
      category:"veg",
      rating:1.2
     },
     { ImageUrl:'B:\rtrppics\vegpulav.jpg',
      name:"Vegpulav",
      price:260,
      discription:"",
      category:"veg",
      rating:3.1
     },
     
     
     
   
]